import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FlagBrazil, FlagIsrael } from './flags';
import dataProperties from './data/properties';
import { dataTransport } from './data/transport';
import { dataTax } from './data/tax';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Idea: Capitalist, Socialist, Communism
// Events: Differen countires subject to different events, suprise

interface Property {
  country: string;
  rent: number[];
  price?: number;
  houseCost: number;
  hotelCost: number;
}



interface Tile {
  type: "corner"| "card" | "property" | "tax" | "suprise" | "communityChest" | "airport",
  name: string;
  rent?: number[],
  price?: number;
  houseCost?: number;
  hotelCost?: number;
  country?: string;
  amount?: string;
}

const dataCompanies = {
  price: 150,
  rent: [4, 10],
  properties: [
    {
      name: "Electric Company"
    },
    {
      name: "Water Company"
    }
  ]
}

const dataCorners = [
  {
    name: "Start",
  },
  {
    name: "Jail"
  },
  {
    name: "Vacation"
  },
  {
    name: "Go to prison"
  }
]

const boardData:Tile[] = [
  {
    type: "corner",
    name: "Start"
  },
  {
    dataProperties[0],
  },
  {
    type: "communityChest",
    name: "Tresure",
  },
  
  {
    type: "corner",
    name: "Passing By - Jail",
  }
]

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
